spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3307/jwbook
    username: root
    password: Pa$$w0rd
  mvc:
    static-path-pattern: /static/**
    view:
      prefix: /WEB-INF/jsp/
      suffix: .jsp
  application:
    name: JWBook
    
mybatis:
  mapper-locations: mappers/*Mapper.xml